services:
  - type: web
    name: f1-backend
    env: docker
    dockerfilePath: Dockerfile  # Path to the Dockerfile in your repo
    buildCommand: ""  # Optional: leave blank since Dockerfile will build the image
    startCommand: "uvicorn main:app --host 0.0.0.0 --port 8000"
    envVars:
      - key: PORT
        value: "8000"
    plan: free
