services:
  - type: web
    name: f1-backend
    env: docker
    dockerfilePath: Dockerfile  # or backend/Dockerfile if it's in a subfolder
    plan: free
    autoDeploy: true
    envVars:
      - key: PORT
        value: "8000"
          # - key: ENV
          #  value: production
